name: release-ubuntu-22.04

on:
  push:
    paths:
      - 'include/version.mk'
      - '.github/workflows/**'
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Check Server Performance
      run: |
        echo "警告⚠"
        echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
        echo -e "已知CPU型号（降序）：7763，8370C，8272CL，8171M，E5-2673 \n"
        echo "--------------------------CPU信息--------------------------"
        echo "CPU物理数量：$(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo -e "CPU核心信息：$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
        echo "--------------------------内存信息--------------------------"
        echo "已安装内存详细信息："
        echo -e "$(sudo lshw -short -C memory | grep GiB) \n"
        echo "--------------------------硬盘信息--------------------------"
        echo "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

    - name: Prerequisites
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt update
        sudo apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget -y

    - name: Checkout
      uses: actions/checkout@v4

    # - name: Setup Debug Session
    #   uses: csexton/debugger-action@master

    - name: Checkout openwrt
      run: git clone --depth 1 https://github.com/openwrt/openwrt.git

    - name: Feeds
      run: |
        cd openwrt
        cp ../debugger-action/default.config .config
        git rev-parse HEAD
        make defconfig
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Make
      run: |
        cd openwrt
        echo -e "$(($(nproc) + 4)) thread compile"
        export FORCE_UNSAFE_CONFIGURE=1
        make -j$(($(nproc) + 4)) || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT 

    - name: Tar
      run: |
        du -sh openwrt/*
        mv openwrt/bin FIRMWARE
 
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: firmware
        path: FIRMWARE
