name: release-ubuntu-22.04

on:
  push:
    paths:
      - 'include/version.mk'
      - '.github/workflows/**'
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Check Server Performance
      run: |
        echo "警告⚠"
        echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
        echo -e "已知CPU型号（降序）：7763，8370C，8272CL，8171M，E5-2673 \n"
        echo "--------------------------CPU信息--------------------------"
        echo "CPU物理数量：$(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo -e "CPU核心信息：$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
        echo "--------------------------内存信息--------------------------"
        echo "已安装内存详细信息："
        echo -e "$(sudo lshw -short -C memory | grep GiB) \n"
        echo "--------------------------硬盘信息--------------------------"
        echo "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

    - name: Prerequisites
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt update
        sudo apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget -y

    # - name: Checkout
    #   uses: actions/checkout@v4

    # - name: Setup Debug Session
    #   uses: csexton/debugger-action@master

    - name: Checkout openwrt
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        git rev-parse HEAD
        git checkout f750e3096f

    - name: Feeds
      run: |
        cd openwrt
        echo -e 'CONFIG_TARGET_qualcommax=y\nCONFIG_TARGET_qualcommax_ipq60xx=y\nCONFIG_SIGNED_PACKAGES=y\nCONFIG_TARGET_qualcommax_ipq60xx_DEVICE_jdcloud_re-ss-01=y' > .config
        echo -e 'src-git packages https://git.openwrt.org/feed/packages.git^025c0c58b3b226b1d4b2a2c4cbc7e3f76d9dba9b\nsrc-git luci https://git.openwrt.org/project/luci.git^f0ff5612a1200803069fab48fa0521909e6a8e48\nsrc-git routing https://git.openwrt.org/feed/routing.git^bdf571c0ea5b9b029707787e0f89be7bbd3d75e3\nsrc-git telephony https://git.openwrt.org/feed/telephony.git^c5652e69f293620548b2276f5a8983f7c1589e48\nsrc-git video https://github.com/openwrt/video.git^094bf58da6682f895255a35a84349a79dab4bf95' > feeds.conf.default
        make defconfig
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Make
      run: |
        cd openwrt
        echo -e "$(($(nproc) + 4)) thread compile"
        export FORCE_UNSAFE_CONFIGURE=1
        make -j$(($(nproc) + 4)) V=s || make -j1 V=s
        du -sh *
        du -sh ../openwrt
        echo "status=success" >> $GITHUB_OUTPUT 
 
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: firmware
        path: openwrt/bin
